### PR TITLE
Endpoints changes

### PR DESCRIPTION
**Pull request by ElieTaillard**
Here are various changes made to the endpoints:
- Modified the route /new_token to /token
- Added the route /decaptcha/pirate (to separate the pirate and lobby parts)
- Added the route /decaptcha/lobby (to separate the pirate and lobby parts)

### CODE REVIEW

**Comment by ikagod** [comment]
Great work, I think if you'd somehow manage to make the deprecated_decaptcha function use the other two new functions instead of having a lage part of their code duplicated then it would be perfect!

**Review by ikagod — APPROVED** [review]
Great work, I think if you'd somehow manage to make the deprecated_decaptcha function use the other two new functions instead of having a lage part of their code duplicated then it would be perfect!

**Comment by ElieTaillard** [comment]
> Great work, I think if you'd somehow manage to make the deprecated_decaptcha function use the other two new functions instead of having a lage part of their code duplicated then it would be perfect!

Given that the data parameters are no longer the same, it will be difficult to achieve this without making the code more complex

**Comment by ElieTaillard** [comment]
I'm merging the modification and if anyone wants to refactor the code afterwards, they're free to do so

**Pull request merged**
