### PR TITLE
Playwright + Chromium to make generation faster, and more unique tokens

### PR DESCRIPTION
**Pull request by susikaman**
Using Playwright's Chromium to achieve more diversity, making every generated token around 95% unique. (Unique) generation is over twice as fast compared to Selenium, around 2.5s/gen.

### CODE REVIEW

**Comment by ikagod** [comment]
Please modify the requirements.txt file to reflect all the new packages necessary for this PR to work.

**Comment by susikaman** [comment]
> Please modify the requirements.txt file to reflect all the new packages necessary for this PR to work.

Updated. Also, it's good to know that Playwright needs to download the webdrivers separately after installation. 'playwright install'

**Comment by ElieTaillard** [comment]
I prefer this solution over Selenium due to its faster execution times. Especially considering that it will be easier to deploy since it only requires using the `python -m playwright install` command. In contrast, with Selenium, the installation of the chromedriver is more cumbersome

**Comment by ElieTaillard** [comment]
With Docker and gunicorn tokens are generated arround 13 seconds

**Pull request merged**
