### PR TITLE
Identify users to have personal tokens

### PR DESCRIPTION
**Pull request by susikaman**
Simple working concept for making individual tokens based on the user's encoded email address. Only requires Ikabot clients to encode self.mail and send it to the API as an additional param.

### CODE REVIEW

**Comment by ikagod** [comment]
We should not have any kind of saving of the user_id anywhere on the API. Instead the user_id should be used as a kind of "seed" that provides randomness based on which the browser configuration is generated. Also, simply changing the user agent isn't enough. I think we should find more properties of the playwright client that can be set and determined by the user_Id.

**Comment by susikaman** [comment]
> We should not have any kind of saving of the user_id anywhere on the API. Instead the user_id should be used as a kind of "seed" that provides randomness based on which the browser configuration is generated. Also, simply changing the user agent isn't enough. I think we should find more properties of the playwright client that can be set and determined by the user_Id.



That would literally be the purpose of the user_ID, generating more personal tokens for each unique client. As of right now, there's only the useragent creating diversity in the tokens and there doesn't seem to be any need for more diversity. 

The point of using user-specific settings for token generation is to battle the issue of account locks caused by blackbox token spam. The mail is used as the seed for simplicity, as it's always the same for each lobby. That could easily be encrypted for additional security if one desires. I can't think of any better way of having a constant seed for clients to use in order to identify clients securely. 

To clarify, changing the useragent causes most of the diversity in tokens. The ony way of causing even more diversity would be changing the locale, country code and browser itself, which have been attempted before but was scrapped due to invalidity of tokens. But as mentioned and proven, the current diversity is good enough for high validity rate.

**Comment by ElieTaillard** [comment]
@ikagod are you thinking of something like this for generating user agent with a seed?
```
def generate_user_agent_from_seed(seed):
    return (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
        + seed
    )
```

**Comment by ikagod** [comment]
> @ikagod are you thinking of something like this for generating user agent with a seed?
> 
> ```
> def generate_user_agent_from_seed(seed):
>     return (
>         "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
>         + seed
>     )
> ```

No because that would probably generate invalid tokens.

> As of right now, there's only the useragent creating diversity in the tokens and there doesn't seem to be any need for more diversity.

It is news to me that the only difference between two different playwright instances is the user agent... I though there were more browser identifying properties that are used during the generation of the blackbox token.

Although if that really is so, and it's enough to just change the user-agent of the browser, then I propose instead of using the fake user-agent package, we simply make our own list of user agents and then pull one out at random, given a seed.

The seed would basically be a number that we divide by the length of the user-agent list and then return the user-agent that is in the index of the remained of that division operation. It's worth noting that if we ever expand the list, one seed that was giving for example a Firefox user-agent, could now be giving a completely different user-agent (like some chrome variant for example) for obvious reasons.

[Here](https://github.com/fake-useragent/fake-useragent/blob/master/src/fake_useragent/data/browsers.json) is a list of all user-agents that the fake user-agent package uses. I think we should probably expand it quite a bit before baking it into the API because once that is done, then it's done forever and modifications to the list can not be made.

**Comment by ElieTaillard** [comment]
I have a question : what happens if we use a single user agent for everyone like in Ikabot?

**Comment by susikaman** [comment]
> I have a question : what happens if we use a single user agent for everyone like in Ikabot?

The issue which started this whole thing; Tokens getting invalidated upon generation due to blacklisted useragent.

**Comment by ElieTaillard** [comment]
When using FakeUserAgent().random for the Chromium browser in Playwright, I've noticed that it may generate a user agent that doesn't match Chromium. I'm not sure if this is a problem, but I want to point it out. Additionally, upon closer examination of the Fake User Agent library, it seems that some user agents are uncommon, which could lead to token invalidation issues. On the flip side, using these less common user agents might contribute to generating unique and potentially valid tokens.

Another consideration is that the library only contains 50 user agents, so I'm uncertain if this is a sufficient number for achieving diversity. I'm also a bit puzzled about why using the same user agent by two people would result in an invalid token, especially considering that there is a popular user agent with a 21% usage, and possibly even more for Ikariam.

**Comment by ikagod** [comment]
> I'm also a bit puzzled about why using the same user agent by two people would result in an invalid token

Because the user agent is not the only parameter that is measured and used by the game1.js script to generate the token, just one of many. I suspect that when a token gets invalidated, the user-agent that created that token becomes invalid as well, although this is just a wild guess.

> I have a question : what happens if we use a single user agent for everyone like in Ikabot?

Because the tokens it generates will become invalid, and anyone who uses them will get their account locked for 12h.

We still know relatively little about the issues at hand (which is that sometimes a user's account can get "browser locked" if they log in too many times using too many different blackbox tokens). One piece of good news is that when two different (real) browser instances are used, and they both keep logging eachother out, neither will ever get invalidated / browser locked, this was tested by Panos.

**Pull request closed without merging**
