### PR TITLE
Playwright Optimised

### PR DESCRIPTION
**Pull request by ElieTaillard**
- Implementation of Playwright as suggested by @johnvittu
- Implementation of PlaywrightContext to have a single instantiation of Playwright and thus gain execution time
- Refactoring of the architecture to use Flask blueprint
- Logger configuration
- Update of gunicorn configuration and dockerfile
- Test corrections

Here are the results that I obtain in real-world conditions:

**Local Flask Execution**
image

**Docker and Gunicorn Setup**
image

For your information, the Docker image weighs 2.8GB. 
Regarding the Gunicorn configuration, it can be adjusted to enhance performance.

### CODE REVIEW

**Comment by susikaman** [comment]
Use caution with the Context feature. When I used the Context feature to modify even more factors for unique tokens, they were generated invalid. It might be something else that went wrong, but the issue was solved once I scrapped the Context part.

**Comment by ElieTaillard** [comment]
Playwrightcontext is a context manager class that I've created myself in order to have a single instance of playwright. It also allows you to have a single browser that remains running throughout the application's lifetime. I haven't tested whether this affects the validity of tokens, but if it does, I'd prefer the first solution proposed by your PR, even if it means losing response time

**Comment by susikaman** [comment]
> Playwrightcontext is a context manager class that I've created myself in order to have a single instance of playwright. It also allows you to have a single browser that remains running throughout the application's lifetime. I haven't tested whether this affects the validity of tokens, but if it does, I'd prefer the first solution proposed by your PR, even if it means losing response time

If you manage to make it work so the validity stays, good! I didn't bother to research it further, since it's not really that necessary as long as the "main" diversity method works. But it surely can be made so that the driver is kept open in the background for quicker generation.

**Comment by ElieTaillard** [comment]
How do I check that the tokens generated are valid?

**Pull request closed without merging**
